### ISSUE TITLE
missing call to InstrEndLoop

### ISSUE THREAD

**Issue by tvondra** [dalibo/pg_qualstats#11]
pgqs_ExecutorEnd gets called before regular ExecutorEnd, which means the instrumentation may not be finalized - there may still be data from the last loop in some of the nodes. pgqs_collectNodeStats needs to do something like this:

	if (planstate->instrument)
		InstrEndLoop(planstate->instrument);

similarly to ExplainNode().

**Comment by rjuju** [comment]
Indeed. I wasn't aware of that, thank a lot for the report and the fix!  It's fixed in 7ad33fb19d04e1f1941cf6b16383237348caad8b
