### ISSUE TITLE
missing 0.0.8

### ISSUE THREAD

**Issue by sttachoires** [dalibo/pg_qualstats#2]
Isn't pg_qualstats--0.0.8.sql missing?
Because:
capa4it=# create extension pg_qualstats;
ERROR:  could not stat file "/tech/postgres/9.4.1/server/share/extension/pg_qualstats--0.0.8.sql": No such file or directory
capa4it=#

**Comment by jmealo** [comment]
I'm having the same issue.

**Comment by jmealo** [comment]
@sttachoires in the meantime, I used this to get started:
```
git clone https://github.com/dalibo/pg_qualstats.git
git checkout 38cc86a9f74899b8bac8256b3f389af6bf1626dd
make
sudo make install
```

**Comment by sttachoires** [comment]
@jmealo I have the 0.0.7 copied to 0.0.8, and it do the trick.

**Comment by rdunklau** [comment]
Sorry for the mistake, 0.0.9 has just been released to fix that.
